version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - errcheck
    - goconst
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unused

  settings:
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - github.com/oasisprotocol/oasis-web3-gateway
            - github.com/oasisprotocol/oasis-core
            - github.com/oasisprotocol/oasis-sdk
            - github.com/ethereum/go-ethereum
            - github.com/gorilla/mux
            - github.com/gorilla/websocket
            - github.com/knadh/koanf
            - github.com/prometheus/client_golang/prometheus
            - github.com/rs/cors
            - github.com/spf13/cobra
            - github.com/stretchr/testify
            - github.com/uptrace/bun
            - github.com/cockroachdb/pebble
            - golang.org/x/crypto
            - google.golang.org/grpc
          deny:
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package
            - pkg: github.com/fxamacker/cbor/v2
              desc: Use oasis-core/go/common/cbor instead

  exclusions:
    generated: lax
    rules:
      # Exclude some linters on test files.
      - linters:
          - govet
          - revive
          - gosec
          - errcheck
        path: (.+)_test\.go
      - linters:
          - govet
          - revive
          - gosec
        path: tests/*
      # Exclude var-naming.
      - linters:
          - revive
        text: var-naming
      # Exclude sttutering.
      - linters:
          - revive
        text: and that stutters
      # Exclude unused parameters.
      - linters:
          - revive
        text: unused-parameter
      # Exclude required comments on exported structs/fields.
      - linters:
          - revive
        text: "exported:"
      # Exclude could apply De Morgan's law.
      - linters:
          - staticcheck
        text: QF1001
      # Exclude could remove embedded fields.
      - linters:
          - staticcheck
        text: QF1008
      # Exclude intiger overflow conversion.
      - linters:
          - gosec
        text: G115
      # Exclude audited unsafe calls.
      - linters:
          - gosec
        text: G103

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/oasisprotocol/
