# golangci-lint configuration.

# For more information, see:
# https://golangci-lint.run/usage/configuration/.

run:
  timeout: 5m

linters:
  # Disable all linters except the ones explicitly listed below.
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - goheader
    - goimports
    - revive
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - noctx
    - prealloc
    - rowserrcheck
    - staticcheck
    - stylecheck
    - sqlclosecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  exhaustive:
    # Switch statements are to be considered exhaustive if a 'default' case is
    # present, even if all enum members aren't listed in the switch.
    default-signifies-exhaustive: true
  govet:
    # Enabled checking for shadowed variables.
    check-shadowing: true
  goimports:
    # Put local imports after 3rd-party packages.
    local-prefixes: github.com/oasisprotocol/
  gosec:
    excludes:
      # https://github.com/securego/gosec#available-rules
      - G402
      - G404
  depguard:
    rules:
      main:
        files:
          - $all
          - "!**/oasis-deposit/*.go"
        allow:
          - $gostd
          - github.com/oasisprotocol
          - google.golang.org/grpc
          - github.com/ethereum/go-ethereum
          - github.com/stretchr/testify
          - github.com/uptrace/bun
          - github.com/gorilla
          - github.com/prometheus
          - github.com/knadh/koanf
          - github.com/rs/cors
          - github.com/spf13/cobra
